#let terms = (
  (slug: "term-client", title: [Client], body: [An immutable handle binding one validated role configuration to restart-stable process names. A correlated client view shares those processes.]),
  (slug: "term-provider", title: [Provider], body: [The configured OpenID issuer and the endpoints and signing keys authenticated through its discovery and transport policy.]),
  (slug: "term-cache-incarnation", title: [Cache incarnation], body: [One live provider-cache process with its own accepted snapshot and fetch ownership. A replacement process has a different incarnation even when its registered name is unchanged.]),
  (slug: "term-provider-snapshot", title: [Provider snapshot], body: [The metadata and signing-key set accepted by one cache incarnation. It is observed provider evidence, not a substitute for configured policy.]),
  (slug: "term-login-transaction", title: [Login transaction], body: [A single-use pending authorization-code login bound to one client, exact redirect, state, nonce, PKCE verifier, browser binding and expiry.]),
  (slug: "term-browser-binding", title: [Browser binding], body: [The random cookie value tying pending login transactions to one browser. It is distinct from the application's authenticated session.]),
  (slug: "term-verified-identity", title: [Verified identity], body: [The checked identity evidence obtained from an ID token for a consumed login transaction. Its stable key is the pair of issuer and subject.]),
  (slug: "term-session", title: [Session], body: [An opaque view of confirmed custody containing verified identity, reference and revision. It is neither a token bag nor a business permission grant.]),
  (slug: "term-session-reference", title: [Session reference], body: [A random bearer value naming custody. A reference proves neither that custody still exists nor that the caller may perform a business operation.]),
  (slug: "term-custody", title: [Custody], body: [Warden's authority over session identity, authentication evidence and token generations in sealed records. It owns installation, refresh transitions and termination.]),
  (slug: "term-store-version", title: [Store version], body: [The compare-and-set concurrency value of a stored row. It is distinct from the token revision and advances on record writes such as refresh reservation or idle touch.]),
  (slug: "term-token-revision", title: [Token revision], body: [The generation number of the material exposed by a session. It advances when refreshed material is published.]),
  (slug: "term-refresh-dispatch", title: [Refresh dispatch], body: [The fresh custody reservation authorizing one provider refresh call for one token revision. Possession of an old session or a waiting result does not create it.]),
  (slug: "term-refresh-lease", title: [Refresh lease], body: [The wall-clock interval during which an outstanding refresh reservation may settle normally. Expiry withdraws permission to resend the predecessor.]),
  (slug: "term-quarantine", title: [Quarantine], body: [Custody's refusal to dispatch a token generation whose provider outcome or accepted response is unsafe to reuse. It retains uncertainty rather than proving revocation.]),
  (slug: "term-custody-recovery", title: [Custody recovery], body: [An owner-bound opaque installation command retained after uncertain custody acknowledgement. It can repeat installation of the same evidence without repeating code exchange.]),
  (slug: "term-refresh-recovery", title: [Refresh recovery], body: [An owner-bound opaque publication command holding already received refreshed material. It cannot authorize another provider request.]),
  (slug: "term-send-evidence", title: [Send evidence], body: [The distinction between proven no transmission and possible provider receipt. A timeout or connection failure after submission cannot prove no send.]),
  (slug: "term-access-claims", title: [Access claims], body: [An opaque checked JWT access-token view for one validator's issuer and resource policy. Application authorization remains a separate decision.]),
  (slug: "term-action", title: [Action], body: [The closed caller response classification Reauthenticate, RetryLater, Recover, FixConfiguration or RejectRequest. It classifies recovery meaning rather than generic retryability.]),
  (slug: "term-sealing-key-ring", title: [Sealing key ring], body: [One current AES-256-GCM key and retired keys permitted for opening older records. Its lifecycle is controlled by the application for durable stores.]),
  (slug: "term-tombstone", title: [Tombstone], body: [A bounded terminal record preserving consumption or termination evidence after secret material is removed. It prevents replay and late installation recovery within its retention horizon.]),
)
